[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
tdp_solana = "2FUi3XvEWg9N4nMzzqX13EQ7cz2nN7FNn9afRAPWhW1h"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
