[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
tdp_solana = "BiwY71TrdBzgv2yfa6KfUxUMY8UCpeiUMGnwmCMTsfs9"

[programs.devnet]
tdp_solana = "BiwY71TrdBzgv2yfa6KfUxUMY8UCpeiUMGnwmCMTsfs9"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
